#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="10"  
A="20"  # Cubic lattice constant
ELEMENTS="['Ni', 'P']"  # Elements
NUMBERS="[8, 2]"  # Number corresponding to each element
COORDS="'../templates/poscar/256.txt'"  # Starting coordinates
SAVE="'../runs'"  # Location to save POSCAR
INCAR="'../templates/incar/test'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen.sh'"  # The submit file

cd ../scripts
${PYTHON} generate_hold_runs.py "${A}" "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}"  "${POTCAR}" "${SUB}"
