#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[10, 12, 14, 16, 18, 20]"  # List of cubic lattice constants
ELEMENTS="['Zr', 'Cu', 'Al']"  # Elements
NUMBERS="[50, 40, 10]"  # Number corresponding to each element
COORDS="'../templates/poscar/256.txt'"  # Starting coordinates
SAVE="'../runs/holds/Zr50Cu40Al10/2000K/4ps'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K_4ps'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}"  "${POTCAR}" "${SUB}"
