#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[11.40018162, 12.40608, 13.41197838, 14.41787676, 15.42377514]"  # List of cubic lattice constants
ELEMENTS="['Ca', 'Mg', 'Cu']"  # Elements
NUMBERS="[55, 25, 20]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../runs/holds/Ca55Mg25Cu20/200K/3ps'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_200K_3ps'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}" "${POTCAR}" "${SUB}"
