#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[11.23595373, 12.22736141, 13.21876909, 14.21017677, 15.20158445]"  # List of cubic lattice constants
ELEMENTS="['Ca', 'Mg', 'Cu']"  # Elements
NUMBERS="[55, 10, 35]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../../runs/Ca55Mg10Cu35/2000K'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}" "${POTCAR}" "${SUB}"
