#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[11.8, 11.9, 11.95, 11.1, 11.2]"  # List of cubic lattice constants
ELEMENTS="['Cu', 'Zr', 'Ag', 'Al']"  # Elements
NUMBERS="[44, 44, 6, 6]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../runs/holds/Cu44Zr44Ag6Al6/2000K/3ps'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K_3ps'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_yipeng.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}" "${POTCAR}" "${SUB}"
