#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[9.49887061, 10.33700626, 11.1751419, 12.01327754, 12.85141318]"  # List of cubic lattice constants
ELEMENTS="['Cu', 'Zr', 'Ag', 'Al']"  # Elements
NUMBERS="[45, 45, 7, 3]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../runs/holds/Cu45Zr45Ag7Al3/2000K/3ps'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K_3ps'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}" "${POTCAR}" "${SUB}"
