#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[9.38981984, 10.21833335, 11.04684687, 11.87536038, 12.7038739]"  # List of cubic lattice constants
ELEMENTS="['Cu', 'Zr', 'Ag']"  # Elements
NUMBERS="[54, 36, 10]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../runs/holds/Cu54Zr36Ag10/200K/3ps'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_200K_3ps'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}" "${POTCAR}" "${SUB}"
