#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[9.2279744, 10.04220743, 10.85644047, 11.6706735, 12.48490654]"  # List of cubic lattice constants
ELEMENTS="['Cu', 'Zr']"  # Elements
NUMBERS="[64, 36]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../runs/holds/Cu64Zr36/200K/3ps'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_200K_3ps'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}" "${POTCAR}" "${SUB}"
