#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[10.5, 11, 11.5]"  # List of cubic lattice constants
ELEMENTS="['Ni', 'P']"  # Elements
NUMBERS="[80, 20]"  # Number corresponding to each element
COORDS="'../templates/poscar/256.txt'"  # Starting coordinates
SAVE="'../runs/holds/Ni80P20/2000K/3ps'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K_3ps'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}"  "${POTCAR}" "${SUB}"
