#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[8.23167569, 8.95800002, 9.68432435, 10.41064867, 11.136973]"  # List of cubic lattice constants
ELEMENTS="['Ni', 'P']"  # Elements
NUMBERS="[80, 20]"  # Number corresponding to each element
SAVE="'../../runs/Ni80P20/2000K'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}"  "${POTCAR}" "${SUB}"
