#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[4.49506517, 4.65769016, 4.82031515, 4.98294014, 5.14556513]"  # List of cubic lattice constants
ELEMENTS="['Ni', 'P']"  # Elements
NUMBERS="[8, 2]"  # Number corresponding to each element
SAVE="'../../runs/Ni8P2/2000K'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}"  "${POTCAR}" "${SUB}"
