#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[11.9, 12.5, 12.25]"  # List of cubic lattice constants
ELEMENTS="['Zr', 'Cu', 'Pd', 'Ag', 'Al']"  # Elements
NUMBERS="[48, 34, 2, 8, 8]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../runs/holds/Zr48Cu34Pd2Ag8Al8/2000K/3ps'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K_3ps'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_yipeng.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}" "${POTCAR}" "${SUB}"
