#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[9.50139634, 10.33975484, 11.17811334, 12.01647184, 12.85483034]"  # List of cubic lattice constants
ELEMENTS="['Zr', 'Cu', 'Al', 'Ag']"  # Elements
NUMBERS="[48, 42, 7, 3]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../../runs/Zr48Cu42Al7Ag3/200K'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_200K'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}" "${POTCAR}" "${SUB}"
