#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[9.45508783, 10.28936029, 11.12363274, 11.9579052, 12.79217766]"  # List of cubic lattice constants
ELEMENTS="['Zr', 'Cu']"  # Elements
NUMBERS="[50, 50]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../../runs/Zr50Cu50/2000K'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}"  "${POTCAR}" "${SUB}"
