#!/bin/bash

# Programs
PYTHON=python3

# Input paramters
RUNS="[9.49936923, 10.33754887, 11.17572851, 12.01390815, 12.85208779]"  # List of cubic lattice constants
ELEMENTS="['Zr', 'Cu', 'Al']"  # Elements
NUMBERS="[50, 40, 10]"  # Number corresponding to each element
COORDS="'../templates/poscar/365.txt'"  # Starting coordinates
SAVE="'../../runs/Zr50Cu40Al10/2000K'"  # Location to save POSCAR
INCAR="'../templates/incar/temperature_2000K'"  # The VASP input file
KPOINTS="'../templates/kpoints/M'"  # The VASP kpoints file
POTCAR="'/home/leschultz/work/POTCARs/paw/LDA/5.4'"  # The VASP potential directory
SUB="'../templates/submit/bardeen_morgan.q'"  # The submit file

cd ../../scripts
${PYTHON} generate_hold_runs.py "${ELEMENTS}" "${NUMBERS}" "${COORDS}" "${SAVE}" "${RUNS}" "${INCAR}" "${KPOINTS}"  "${POTCAR}" "${SUB}"
